### ISSUE TITLE
Issue with apex dependency

### ISSUE THREAD

**Issue by taylorshin** [amzn/zero-shot-rlhr#1]
Interesting paper! I tried running the training script but ran into the following error regarding the apex library
```
ImportError: cannot import name 'UnencryptedCookieSessionFactoryConfig' from 'pyramid.session' (unknown location)
```
I made sure to download (via pip) the specific versions of each dependency (except for CUDA, I have version 11.0). I also tried following the suggestion of downloading apex from source in this stackoverflow [post](https://stackoverflow.com/questions/66610378/unencryptedcookiesessionfactoryconfig-error-when-importing-apex) but that didn't help either as I ran into other errors/bugs. According to that post, apex was last updated in 2013 and is no longer maintained. How did you install apex?

**Comment by DanqingZ** [comment]
Hi thank you for your interest in our work! 
The apex package we used is: https://github.com/NVIDIA/apex
You can check the quick start section to see how to install apex. 
```
$ git clone https://github.com/NVIDIA/apex
$ cd apex
$ pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
```
My suggestion for installing apex is that you also need to provide CUDA_HOME path before pip install from source, for example for cuda 11.
```
export CUDA_HOME=/usr/local/cuda-11.0/
```
