### ISSUE TITLE
No change in training loss 

### ISSUE THREAD

**Issue by kandalav** [amzn/zero-shot-rlhr#2]
Hi, 

First of all, thank you for this repository and the experiment. We are trying to implement this and after a lot of work on this, we are noticing that the training loss doesn't change at all. So, we are sure that learning isn't happening but unsure of how to fix it. 

Any suggestions? 

Thanks,
Vaishnavi

**Comment by kandalavaishnavi** [comment]
Sorted this out and we are training on our use case. 

Thanks.
